# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.16.10

# Mod Properties
mod_version=1.0.1+object-Object
maven_group=vg.skye.trinkhide
archives_base_name=trinkhide

# Dependencies
fabric_version=0.92.3+1.20.1
cca_version=5.2.3
trinkets_version=3.7.1