name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release-github:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Remove non-mod jars from artifacts
        run: rm -f build/libs/*-sources.jar build/libs/*-javadoc.jar

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true  # remove if this gets merged into upstream
          files: |
            build/libs/*.jar
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
